### ISSUE TITLE
Request: RetroArch core

### ISSUE THREAD

**Issue by eyeonus** [Nikilites/nuzu#3]
Just putting this out there now, I know the situation so I don't expect any kind of development towards this any time soon.

Please consider making a RetroArch core. That is all.

**Comment by borntohonk** [comment]
> Just putting this out there now, I know the situation so I don't expect any kind of development towards this any time soon.
> 
> Please consider making a RetroArch core. That is all.

didn't exist before takedown, wont exist after takedown.

There are citra cores, but that's because citra has cryptographic keys embedded in codebase, yuzu does not.

**Comment by eyeonus** [comment]
It didn't exist before takedown because the Yuzu development team had personal issues with the RetroArch team, not because of any technological reasons. Specifically, the lead developer for Yuzu told me they weren't going to do it when I asked in the Discord server because, according to that person, "the RetroArch people are dicks".

I personally have had the opposite experience, in that the RetroArch persons I have talked to were all quite helpful and not dickish in the slightest, while the Yuzu people were always very rude to me in any interactions I had with them, so I would tend to believe that it was not, in fact, the RetroArch people that were the "dicks".

Since it is highly unlikely that any of the people that worked on Yuzu will be contributing to this, I think it highly probable that those that do choose to work on this will probably not have the same attitude towards RetroArch and the people involved in that project, and therefore might be willing to consider the idea rather than dismissing it out of hand.

There are a number of emulators for various systems that require *something* from the user's physical hardware in order to operate, such as the PS2 BIOS for PCSX2, or the WII NAND for Dolphin, and those emulators have RetroArch cores. It is demonstrably possible to make a core for RetroArch that is based on an emulator that requires user provided files.

**Comment by Nikilites** [comment]
Since it wasn't there before doesn't mean it's not possible, but it will be very difficult without some developers who know these topics well. If we find someone for that too then we'll be done. But I can't give my word
